sample: {
    '--mind': '0.06',
    '--king-cutoff': '0.0884' # Cutoff corresponds to second degree relatives
}
variant: {
    '--maf': '0.05',
    '--geno': '0.02',
    '--hwe': '0.000001 midp keep-fewhet'
}